/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookACallRouteImport } from './routes/book-a-call'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StartAProjectRouteImport } from './routes/start-a-project'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as WorkRouteImport } from './routes/work'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAboutRouteImport } from './routes/admin.about'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminCallsRouteImport } from './routes/admin.calls'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLogosRouteImport } from './routes/admin.logos'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminRecognitionRouteImport } from './routes/admin.recognition'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminWorkRouteImport } from './routes/admin.work'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ResourcesBlogSlugRouteImport } from './routes/resources.blog.$slug'
import { Route as ResourcesDownloadsSlugRouteImport } from './routes/resources.downloads.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookACallRoute = BookACallRouteImport.update({
  id: '/book-a-call',
  path: '/book-a-call',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StartAProjectRoute = StartAProjectRouteImport.update({
  id: '/start-a-project',
  path: '/start-a-project',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCallsRoute = AdminCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogosRoute = AdminLogosRouteImport.update({
  id: '/logos',
  path: '/logos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecognitionRoute = AdminRecognitionRouteImport.update({
  id: '/recognition',
  path: '/recognition',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkRoute = AdminWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AdminRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)
const ResourcesBlogSlugRoute = ResourcesBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesDownloadsSlugRoute = ResourcesDownloadsSlugRouteImport.update({
  id: '/downloads/$slug',
  path: '/downloads/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-a-call': typeof BookACallRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRoute
  '/start-a-project': typeof StartAProjectRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/work': typeof WorkRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/calls': typeof AdminCallsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logos': typeof AdminLogosRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recognition': typeof AdminRecognitionRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/work': typeof AdminWorkRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/resources/blog/$slug': typeof ResourcesBlogSlugRoute
  '/resources/downloads/$slug': typeof ResourcesDownloadsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-a-call': typeof BookACallRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/start-a-project': typeof StartAProjectRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/calls': typeof AdminCallsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logos': typeof AdminLogosRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recognition': typeof AdminRecognitionRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/work': typeof AdminWorkRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin': typeof AdminIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/work': typeof WorkIndexRoute
  '/resources/blog/$slug': typeof ResourcesBlogSlugRoute
  '/resources/downloads/$slug': typeof ResourcesDownloadsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-a-call': typeof BookACallRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRoute
  '/start-a-project': typeof StartAProjectRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/work': typeof WorkRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/calls': typeof AdminCallsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logos': typeof AdminLogosRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recognition': typeof AdminRecognitionRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/work': typeof AdminWorkRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/resources/blog/$slug': typeof ResourcesBlogSlugRoute
  '/resources/downloads/$slug': typeof ResourcesDownloadsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book-a-call'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/start-a-project'
    | '/terms'
    | '/thank-you'
    | '/work'
    | '/admin/about'
    | '/admin/admins'
    | '/admin/blogs'
    | '/admin/calls'
    | '/admin/contact'
    | '/admin/home'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/logos'
    | '/admin/projects'
    | '/admin/recognition'
    | '/admin/resources'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/testimonials'
    | '/admin/work'
    | '/work/$slug'
    | '/admin/'
    | '/resources/'
    | '/work/'
    | '/resources/blog/$slug'
    | '/resources/downloads/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-a-call'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/privacy'
    | '/services'
    | '/start-a-project'
    | '/terms'
    | '/thank-you'
    | '/admin/about'
    | '/admin/admins'
    | '/admin/blogs'
    | '/admin/calls'
    | '/admin/contact'
    | '/admin/home'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/logos'
    | '/admin/projects'
    | '/admin/recognition'
    | '/admin/resources'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/testimonials'
    | '/admin/work'
    | '/work/$slug'
    | '/admin'
    | '/resources'
    | '/work'
    | '/resources/blog/$slug'
    | '/resources/downloads/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/book-a-call'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/start-a-project'
    | '/terms'
    | '/thank-you'
    | '/work'
    | '/admin/about'
    | '/admin/admins'
    | '/admin/blogs'
    | '/admin/calls'
    | '/admin/contact'
    | '/admin/home'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/logos'
    | '/admin/projects'
    | '/admin/recognition'
    | '/admin/resources'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/testimonials'
    | '/admin/work'
    | '/work/$slug'
    | '/admin/'
    | '/resources/'
    | '/work/'
    | '/resources/blog/$slug'
    | '/resources/downloads/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookACallRoute: typeof BookACallRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  StartAProjectRoute: typeof StartAProjectRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-call': {
      id: '/book-a-call'
      path: '/book-a-call'
      fullPath: '/book-a-call'
      preLoaderRoute: typeof BookACallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-a-project': {
      id: '/start-a-project'
      path: '/start-a-project'
      fullPath: '/start-a-project'
      preLoaderRoute: typeof StartAProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calls': {
      id: '/admin/calls'
      path: '/calls'
      fullPath: '/admin/calls'
      preLoaderRoute: typeof AdminCallsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logos': {
      id: '/admin/logos'
      path: '/logos'
      fullPath: '/admin/logos'
      preLoaderRoute: typeof AdminLogosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recognition': {
      id: '/admin/recognition'
      path: '/recognition'
      fullPath: '/admin/recognition'
      preLoaderRoute: typeof AdminRecognitionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/work': {
      id: '/admin/work'
      path: '/work'
      fullPath: '/admin/work'
      preLoaderRoute: typeof AdminWorkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
    '/resources/blog/$slug': {
      id: '/resources/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/resources/blog/$slug'
      preLoaderRoute: typeof ResourcesBlogSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/downloads/$slug': {
      id: '/resources/downloads/$slug'
      path: '/downloads/$slug'
      fullPath: '/resources/downloads/$slug'
      preLoaderRoute: typeof ResourcesDownloadsSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminCallsRoute: typeof AdminCallsRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogosRoute: typeof AdminLogosRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminRecognitionRoute: typeof AdminRecognitionRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminWorkRoute: typeof AdminWorkRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminCallsRoute: AdminCallsRoute,
  AdminContactRoute: AdminContactRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogosRoute: AdminLogosRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminRecognitionRoute: AdminRecognitionRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminWorkRoute: AdminWorkRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResourcesRouteChildren {
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ResourcesBlogSlugRoute: typeof ResourcesBlogSlugRoute
  ResourcesDownloadsSlugRoute: typeof ResourcesDownloadsSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesIndexRoute: ResourcesIndexRoute,
  ResourcesBlogSlugRoute: ResourcesBlogSlugRoute,
  ResourcesDownloadsSlugRoute: ResourcesDownloadsSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookACallRoute: BookACallRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ServicesRoute: ServicesRoute,
  StartAProjectRoute: StartAProjectRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
